<template><div><h1 id="数据库实体类" tabindex="-1"><a class="header-anchor" href="#数据库实体类"><span>数据库实体类</span></a></h1>
<p>FastChar 数据库实体类的：FastEntity</p>
<h2 id="介绍" tabindex="-1"><a class="header-anchor" href="#介绍"><span>介绍</span></a></h2>
<p>FastEntity是FastChar核心类之一，在Java与数据库操作的桥梁，也就是ORM的核心类。</p>
<p>FastEntity与我们传统概念中的Dao类似，但是与传统的Dao不同的是FastEntity灵活性更高，使用起来方便快捷！</p>
<h2 id="实现数据库实体类" tabindex="-1"><a class="header-anchor" href="#实现数据库实体类"><span>实现数据库实体类</span></a></h2>
<p>声明一个类并继承FastEntity即可，如下：</p>
<div class="language-java line-numbers-mode" data-ext="java" data-title="java"><pre v-pre class="language-java"><code><span class="token keyword">public</span> <span class="token keyword">class</span> <span class="token class-name">FcUserEntity</span> <span class="token keyword">extends</span> <span class="token class-name">FastEntity</span><span class="token generics"><span class="token punctuation">&lt;</span><span class="token class-name">FcUserEntity</span><span class="token punctuation">></span></span> <span class="token punctuation">{</span>
    <span class="token keyword">public</span> <span class="token keyword">static</span> <span class="token class-name">FcUserEntity</span> <span class="token function">getInstance</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
        <span class="token keyword">return</span> <span class="token class-name">FastChar</span><span class="token punctuation">.</span><span class="token function">getOverrides</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">singleInstance</span><span class="token punctuation">(</span><span class="token class-name">FcUserEntity</span><span class="token punctuation">.</span><span class="token keyword">class</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span>
 
    <span class="token comment">//绑定的表格</span>
    <span class="token annotation punctuation">@Override</span>
    <span class="token keyword">public</span> <span class="token class-name">String</span> <span class="token function">getTableName</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
        <span class="token keyword">return</span> <span class="token string">"fc_user"</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span>
 
    <span class="token annotation punctuation">@Override</span>
    <span class="token keyword">public</span> <span class="token class-name">String</span> <span class="token function">getTableDetails</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
        <span class="token keyword">return</span> <span class="token string">"用户管理"</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span>
 
    <span class="token annotation punctuation">@Override</span>
    <span class="token keyword">public</span> <span class="token keyword">void</span> <span class="token function">setDefaultValue</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
        <span class="token function">set</span><span class="token punctuation">(</span><span class="token string">"userState"</span><span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token function">set</span><span class="token punctuation">(</span><span class="token string">"userDateTime"</span><span class="token punctuation">,</span> <span class="token keyword">new</span> <span class="token class-name">Date</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>以上代码中，方法getTableName是FastEntity的抽象方法，必须实现。用于绑定Entity与数据库中的表格。绑定后即可对表格进行增删查改等一系列数据库操作！</p>
<div class="hint-container warning">
<p class="hint-container-title">注意</p>
<p>以下代码未显式指定数据源，则以系统配置的默认数据源为准。</p>
</div>
<h3 id="插入数据" tabindex="-1"><a class="header-anchor" href="#插入数据"><span>插入数据</span></a></h3>
<div class="language-java line-numbers-mode" data-ext="java" data-title="java"><pre v-pre class="language-java"><code><span class="token class-name">FcUserEntity</span> fcUserEntity <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">FcUserEntity</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
fcUserEntity<span class="token punctuation">.</span><span class="token function">set</span><span class="token punctuation">(</span><span class="token string">"userNickName"</span><span class="token punctuation">,</span> <span class="token string">"用户昵称"</span><span class="token punctuation">)</span><span class="token punctuation">;</span><span class="token comment">//对应表格里的字段 userNickName</span>
fcUserEntity<span class="token punctuation">.</span><span class="token function">set</span><span class="token punctuation">(</span><span class="token string">"userCity"</span><span class="token punctuation">,</span> <span class="token string">"合肥"</span><span class="token punctuation">)</span><span class="token punctuation">;</span><span class="token comment">//对应表格里的字段 userCity</span>
fcUserEntity<span class="token punctuation">.</span><span class="token function">save</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="查询数据" tabindex="-1"><a class="header-anchor" href="#查询数据"><span>查询数据</span></a></h3>
<div class="language-java line-numbers-mode" data-ext="java" data-title="java"><pre v-pre class="language-java"><code><span class="token class-name">FcUserEntity</span> fcUserEntity <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">FcUserEntity</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token comment">//系统会自动将查询的数据所有字段装载到FcUserEntity中</span>
<span class="token class-name">List</span><span class="token generics"><span class="token punctuation">&lt;</span><span class="token class-name">FcUserEntity</span><span class="token punctuation">></span></span> select <span class="token operator">=</span> fcUserEntity<span class="token punctuation">.</span><span class="token function">select</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

<span class="token comment">//获取第一条数据里的userNickName字段值，并自动转换成String类型</span>
<span class="token class-name">String</span> userNickName<span class="token operator">=</span>select<span class="token punctuation">.</span><span class="token function">get</span><span class="token punctuation">(</span><span class="token number">0</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">getString</span><span class="token punctuation">(</span><span class="token string">"userNickName"</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="删除数据" tabindex="-1"><a class="header-anchor" href="#删除数据"><span>删除数据</span></a></h3>
<div class="language-java line-numbers-mode" data-ext="java" data-title="java"><pre v-pre class="language-java"><code><span class="token class-name">FcUserEntity</span> fcUserEntity <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">FcUserEntity</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
fcUserEntity<span class="token punctuation">.</span><span class="token function">set</span><span class="token punctuation">(</span><span class="token string">"userId"</span><span class="token punctuation">,</span> <span class="token number">1</span><span class="token punctuation">)</span><span class="token punctuation">;</span><span class="token comment">//根据表格的主键 userId 删除userId 为 1 的数据</span>
fcUserEntity<span class="token punctuation">.</span><span class="token function">delete</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="修改数据" tabindex="-1"><a class="header-anchor" href="#修改数据"><span>修改数据</span></a></h3>
<div class="language-java line-numbers-mode" data-ext="java" data-title="java"><pre v-pre class="language-java"><code><span class="token comment">//使用entity的set方法设置需要修改的属性值</span>
<span class="token class-name">FcUserEntity</span> fcUserEntity <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">FcUserEntity</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
fcUserEntity<span class="token punctuation">.</span><span class="token function">set</span><span class="token punctuation">(</span><span class="token string">"userId"</span><span class="token punctuation">,</span> <span class="token number">1</span><span class="token punctuation">)</span><span class="token punctuation">;</span><span class="token comment">//根据表格的主键 userId 修改userId 为 1 的数据</span>
fcUserEntity<span class="token punctuation">.</span><span class="token function">set</span><span class="token punctuation">(</span><span class="token string">"userNickName"</span><span class="token punctuation">,</span> <span class="token string">"新的昵称"</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
fcUserEntity<span class="token punctuation">.</span><span class="token function">update</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="属性值为null" tabindex="-1"><a class="header-anchor" href="#属性值为null"><span>属性值为NULL</span></a></h3>
<p>如果需要清空数据库表格中某个属性值，可以设置属性值为字符串 <code v-pre>&quot;&lt;null&gt;&quot;</code> 或者 <code v-pre>null</code> , 如下：</p>
<div class="language-java line-numbers-mode" data-ext="java" data-title="java"><pre v-pre class="language-java"><code><span class="token comment">//使用entity的set方法设置需要修改的属性值</span>
<span class="token class-name">FcUserEntity</span> fcUserEntity <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">FcUserEntity</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token comment">//使用字符串 &lt;null> 值，则数据库会置空属性 userNickName</span>
fcUserEntity<span class="token punctuation">.</span><span class="token function">set</span><span class="token punctuation">(</span><span class="token string">"userNickName"</span><span class="token punctuation">,</span> <span class="token string">"&lt;null>"</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
fcUserEntity<span class="token punctuation">.</span><span class="token function">update</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>或者</p>
<div class="language-java line-numbers-mode" data-ext="java" data-title="java"><pre v-pre class="language-java"><code><span class="token comment">//使用entity的set方法设置需要修改的属性值</span>
<span class="token class-name">FcUserEntity</span> fcUserEntity <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">FcUserEntity</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
fcUserEntity<span class="token punctuation">.</span><span class="token function">set</span><span class="token punctuation">(</span><span class="token string">"userNickName"</span><span class="token punctuation">,</span><span class="token keyword">null</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
fcUserEntity<span class="token punctuation">.</span><span class="token function">update</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="切换数据源" tabindex="-1"><a class="header-anchor" href="#切换数据源"><span>切换数据源</span></a></h3>
<p>开发者可以手动指定使用哪个数据源，如下：</p>
<div class="language-java line-numbers-mode" data-ext="java" data-title="java"><pre v-pre class="language-java"><code><span class="token class-name">FcUserEntity</span> fcUserEntity <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">FcUserEntity</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
fcUserEntity<span class="token punctuation">.</span><span class="token function">setDatabase</span><span class="token punctuation">(</span><span class="token string">"data_source_a"</span><span class="token punctuation">)</span><span class="token punctuation">;</span><span class="token comment">//指定了数据源 data_source_a </span>
fcUserEntity<span class="token punctuation">.</span><span class="token function">set</span><span class="token punctuation">(</span><span class="token string">"userNickName"</span><span class="token punctuation">,</span> <span class="token string">"用户昵称"</span><span class="token punctuation">)</span><span class="token punctuation">;</span><span class="token comment">//对应表格里的字段 userNickName</span>
fcUserEntity<span class="token punctuation">.</span><span class="token function">set</span><span class="token punctuation">(</span><span class="token string">"userCity"</span><span class="token punctuation">,</span> <span class="token string">"合肥"</span><span class="token punctuation">)</span><span class="token punctuation">;</span><span class="token comment">//对应表格里的字段 userCity</span>
fcUserEntity<span class="token punctuation">.</span><span class="token function">save</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="数据库实体的方法" tabindex="-1"><a class="header-anchor" href="#数据库实体的方法"><span>数据库实体的方法</span></a></h2>
<h3 id="setdefaultvalue" tabindex="-1"><a class="header-anchor" href="#setdefaultvalue"><span>setDefaultValue</span></a></h3>
<p>设置属性默认值，在调用save和update方法时会触发，如下：</p>
<div class="language-java line-numbers-mode" data-ext="java" data-title="java"><pre v-pre class="language-java"><code><span class="token keyword">public</span> <span class="token keyword">class</span> <span class="token class-name">FcUserEntity</span> <span class="token keyword">extends</span> <span class="token class-name">FastEntity</span><span class="token generics"><span class="token punctuation">&lt;</span><span class="token class-name">FcUserEntity</span><span class="token punctuation">></span></span> <span class="token punctuation">{</span>
    <span class="token keyword">public</span> <span class="token keyword">static</span> <span class="token class-name">FcUserEntity</span> <span class="token function">getInstance</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
        <span class="token keyword">return</span> <span class="token class-name">FastChar</span><span class="token punctuation">.</span><span class="token function">getOverrides</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">singleInstance</span><span class="token punctuation">(</span><span class="token class-name">FcUserEntity</span><span class="token punctuation">.</span><span class="token keyword">class</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span>
 
    <span class="token comment">//绑定的表格</span>
    <span class="token annotation punctuation">@Override</span>
    <span class="token keyword">public</span> <span class="token class-name">String</span> <span class="token function">getTableName</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
        <span class="token keyword">return</span> <span class="token string">"fc_user"</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span>
 
    <span class="token annotation punctuation">@Override</span>
    <span class="token keyword">public</span> <span class="token class-name">String</span> <span class="token function">getTableDetails</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
        <span class="token keyword">return</span> <span class="token string">"用户管理"</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span>
 
    <span class="token annotation punctuation">@Override</span>
    <span class="token keyword">public</span> <span class="token keyword">void</span> <span class="token function">setDefaultValue</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
        <span class="token comment">//设置了默认值，当 userState 为空时使用默认值 </span>
        <span class="token function">set</span><span class="token punctuation">(</span><span class="token string">"userNickName"</span><span class="token punctuation">,</span> <span class="token string">"默认名"</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span>
<span class="token punctuation">}</span>
</code></pre><div class="highlight-lines"><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><div class="highlight-line">&nbsp;</div><div class="highlight-line">&nbsp;</div><div class="highlight-line">&nbsp;</div><div class="highlight-line">&nbsp;</div><div class="highlight-line">&nbsp;</div></div><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>当执行 <code v-pre>FcUserEntity</code> 的 <code v-pre>save</code> 或 <code v-pre>update</code> 方法时，会触发对象的 <code v-pre>setDefaultValue</code></p>
<div class="hint-container warning">
<p class="hint-container-title">注意</p>
<p><code v-pre>update</code> 方法与 <code v-pre>save</code> 方法触发 <code v-pre>setDefaultValue</code> 不同的是，只有 <code v-pre>set</code> 属性 <code v-pre>userNickName</code> 时 才会触发默认值的判断逻辑，如下:</p>
<div class="language-java line-numbers-mode" data-ext="java" data-title="java"><pre v-pre class="language-java"><code><span class="token class-name">FcUserEntity</span> fcUserEntity <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">FcUserEntity</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
fcUserEntity<span class="token punctuation">.</span><span class="token function">set</span><span class="token punctuation">(</span><span class="token string">"userCity"</span><span class="token punctuation">,</span> <span class="token string">"合肥"</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
fcUserEntity<span class="token punctuation">.</span><span class="token function">update</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token comment">//此时调用触发 setDefaultValue </span>
<span class="token comment">//并不会设置 默认值 userNickName 因为未修改 userNickName 属性</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><div class="language-java line-numbers-mode" data-ext="java" data-title="java"><pre v-pre class="language-java"><code><span class="token class-name">FcUserEntity</span> fcUserEntity <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">FcUserEntity</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
fcUserEntity<span class="token punctuation">.</span><span class="token function">set</span><span class="token punctuation">(</span><span class="token string">"userNickName"</span><span class="token punctuation">,</span> <span class="token keyword">null</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
fcUserEntity<span class="token punctuation">.</span><span class="token function">update</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token comment">//此时调用触发 setDefaultValue</span>
<span class="token comment">//会设置 默认值 userNickName 因为修改了 userNickName 属性</span>
<span class="token comment">//并且设置的值 为空 </span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div>
<h3 id="convertvalue" tabindex="-1"><a class="header-anchor" href="#convertvalue"><span>convertValue</span></a></h3>
<p>转换属性值，当查询实体数据时，会调用此方法，如下：</p>
<div class="language-java line-numbers-mode" data-ext="java" data-title="java"><pre v-pre class="language-java"><code><span class="token keyword">public</span> <span class="token keyword">class</span> <span class="token class-name">FcUserEntity</span> <span class="token keyword">extends</span> <span class="token class-name">FastEntity</span><span class="token generics"><span class="token punctuation">&lt;</span><span class="token class-name">FcUserEntity</span><span class="token punctuation">></span></span> <span class="token punctuation">{</span>
    <span class="token keyword">public</span> <span class="token keyword">static</span> <span class="token class-name">FcUserEntity</span> <span class="token function">getInstance</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
        <span class="token keyword">return</span> <span class="token class-name">FastChar</span><span class="token punctuation">.</span><span class="token function">getOverrides</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">singleInstance</span><span class="token punctuation">(</span><span class="token class-name">FcUserEntity</span><span class="token punctuation">.</span><span class="token keyword">class</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span>
    <span class="token comment">//绑定的表格</span>
    <span class="token annotation punctuation">@Override</span>
    <span class="token keyword">public</span> <span class="token class-name">String</span> <span class="token function">getTableName</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
        <span class="token keyword">return</span> <span class="token string">"fc_user"</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span>
 
    <span class="token annotation punctuation">@Override</span>
    <span class="token keyword">public</span> <span class="token class-name">String</span> <span class="token function">getTableDetails</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
        <span class="token keyword">return</span> <span class="token string">"用户管理"</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span>
 
    <span class="token annotation punctuation">@Override</span>
    <span class="token keyword">public</span> <span class="token keyword">void</span> <span class="token function">convertValue</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
        <span class="token comment">//追加了属性 userPhone2 </span>
        <span class="token function">set</span><span class="token punctuation">(</span><span class="token string">"userPhone2"</span><span class="token punctuation">,</span> <span class="token function">getString</span><span class="token punctuation">(</span><span class="token string">"userPhone"</span><span class="token punctuation">)</span><span class="token operator">+</span><span class="token string">"测试"</span> <span class="token punctuation">)</span><span class="token punctuation">;</span>
        
        <span class="token comment">//全部统一了用户昵称</span>
        <span class="token function">set</span><span class="token punctuation">(</span><span class="token string">"userNickName"</span><span class="token punctuation">,</span><span class="token string">"统一名称"</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span>
<span class="token punctuation">}</span>
</code></pre><div class="highlight-lines"><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><div class="highlight-line">&nbsp;</div><div class="highlight-line">&nbsp;</div><div class="highlight-line">&nbsp;</div><div class="highlight-line">&nbsp;</div><div class="highlight-line">&nbsp;</div><div class="highlight-line">&nbsp;</div><div class="highlight-line">&nbsp;</div></div><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>当使用 <code v-pre>FcUserEntity</code> 对象查询 <code v-pre>fc_user</code> 表格数据时，返回的所有 <code v-pre>FcUserEntity</code> 对象 会调用 <code v-pre>convertValue</code> 方法</p>
</div></template>


