<template><div><h1 id="数据库读写操作jdbc" tabindex="-1"><a class="header-anchor" href="#数据库读写操作jdbc"><span>数据库读写操作JDBC</span></a></h1>
<p>FastChar 默认提供了数据库的读写操作工具了 <code v-pre>FastDB</code> ，开发者可以通过 <code v-pre>FastChar.getDB()</code> 获取工具类对象。</p>
<h2 id="select查询" tabindex="-1"><a class="header-anchor" href="#select查询"><span>select查询</span></a></h2>
<p>方法 <code v-pre>select(String sqlStr, Object... params)</code> 执行sql查询语句，如下：</p>
<div class="language-java line-numbers-mode" data-ext="java" data-title="java"><pre v-pre class="language-java"><code><span class="token keyword">public</span> <span class="token keyword">void</span> <span class="token function">test</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">{</span>
        <span class="token class-name">List</span><span class="token generics"><span class="token punctuation">&lt;</span><span class="token class-name">FastEntity</span><span class="token punctuation">&lt;</span><span class="token operator">?</span><span class="token punctuation">></span><span class="token punctuation">></span></span> select <span class="token operator">=</span> <span class="token class-name">FastChar</span>
                                <span class="token punctuation">.</span><span class="token function">getDB</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
                                <span class="token punctuation">.</span><span class="token function">select</span><span class="token punctuation">(</span><span class="token string">"select * from fc_user where userRole = ? "</span><span class="token punctuation">,</span> <span class="token number">1</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="select分页查询" tabindex="-1"><a class="header-anchor" href="#select分页查询"><span>select分页查询</span></a></h2>
<p>方法 <code v-pre>select(int page, int pageSize, String sqlStr, Object... params) </code> 执行sql分页查询语句，如下：</p>
<div class="language-java line-numbers-mode" data-ext="java" data-title="java"><pre v-pre class="language-java"><code><span class="token keyword">public</span> <span class="token keyword">void</span> <span class="token function">test</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token class-name">FastPage</span><span class="token generics"><span class="token punctuation">&lt;</span><span class="token class-name">FastEntity</span><span class="token punctuation">&lt;</span><span class="token operator">?</span><span class="token punctuation">></span><span class="token punctuation">></span></span> result <span class="token operator">=</span> <span class="token class-name">FastChar</span>
            <span class="token punctuation">.</span><span class="token function">getDB</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">.</span>
            <span class="token function">select</span><span class="token punctuation">(</span><span class="token number">1</span><span class="token punctuation">,</span> <span class="token number">20</span><span class="token punctuation">,</span> <span class="token string">"select * from fc_user where userRole = ? "</span><span class="token punctuation">,</span> <span class="token number">1</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token keyword">int</span> page <span class="token operator">=</span> result<span class="token punctuation">.</span><span class="token function">getPage</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span><span class="token comment">//获取当前页数</span>
    <span class="token keyword">int</span> pageSize <span class="token operator">=</span> result<span class="token punctuation">.</span><span class="token function">getPageSize</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span><span class="token comment">//获取每页大小</span>
    <span class="token keyword">int</span> totalRow <span class="token operator">=</span> result<span class="token punctuation">.</span><span class="token function">getTotalRow</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span><span class="token comment">//获取总行数</span>
    <span class="token class-name">List</span><span class="token generics"><span class="token punctuation">&lt;</span><span class="token class-name">FastEntity</span><span class="token punctuation">&lt;</span><span class="token operator">?</span><span class="token punctuation">></span><span class="token punctuation">></span></span> list <span class="token operator">=</span> result<span class="token punctuation">.</span><span class="token function">getList</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span><span class="token comment">//获取列表数据</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="selectfirst-查询第一条数据" tabindex="-1"><a class="header-anchor" href="#selectfirst-查询第一条数据"><span>selectFirst 查询第一条数据</span></a></h2>
<p>方法 <code v-pre>selectFirst(String sqlStr, Object... params)</code> 执行sql查询语句，并返回第一条数据，如下：</p>
<div class="language-java line-numbers-mode" data-ext="java" data-title="java"><pre v-pre class="language-java"><code><span class="token keyword">public</span> <span class="token keyword">void</span> <span class="token function">test</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token class-name">FastEntity</span><span class="token generics"><span class="token punctuation">&lt;</span><span class="token operator">?</span><span class="token punctuation">></span></span> result <span class="token operator">=</span> <span class="token class-name">FastChar</span>
            <span class="token punctuation">.</span><span class="token function">getDB</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">.</span>
            <span class="token function">selectFirst</span><span class="token punctuation">(</span><span class="token string">"select * from fc_user where userId = ? "</span><span class="token punctuation">,</span> <span class="token number">1</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><div class="hint-container caution">
<p class="hint-container-title">警告</p>
<p>此方法 <code v-pre>selectFirst</code> 作用是获取 sql语句 查询列表的第一条数据，
所以 sql 语句一定要做好条件筛选，避免出现 查询了 几千条 而只返回第一条照成效率问题。</p>
</div>
<h2 id="selectlast-查询最后一条数据" tabindex="-1"><a class="header-anchor" href="#selectlast-查询最后一条数据"><span>selectLast 查询最后一条数据</span></a></h2>
<p>方法 <code v-pre>selectLast(String sqlStr, Object... params)</code> 执行sql查询语句，并返回最后一条数据，如下：</p>
<div class="language-java line-numbers-mode" data-ext="java" data-title="java"><pre v-pre class="language-java"><code><span class="token keyword">public</span> <span class="token keyword">void</span> <span class="token function">test</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token class-name">FastEntity</span><span class="token generics"><span class="token punctuation">&lt;</span><span class="token operator">?</span><span class="token punctuation">></span></span> result <span class="token operator">=</span> <span class="token class-name">FastChar</span>
            <span class="token punctuation">.</span><span class="token function">getDB</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">.</span>
            <span class="token function">selectLast</span><span class="token punctuation">(</span><span class="token string">"select * from fc_user where userRole = ? "</span><span class="token punctuation">,</span> <span class="token number">1</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><div class="hint-container caution">
<p class="hint-container-title">警告</p>
<p>此方法 <code v-pre>selectLast</code> 作用是获取 sql语句 查询列表的最后一条数据，
所以 sql 语句一定要做好条件筛选，避免出现 查询了 几千条 而只返回最后一条照成效率问题。</p>
</div>
<h2 id="update更新数据" tabindex="-1"><a class="header-anchor" href="#update更新数据"><span>update更新数据</span></a></h2>
<p>方法 <code v-pre>update(String sqlStr, Object... params)</code> 执行更新sql语句，如下：</p>
<div class="language-java line-numbers-mode" data-ext="java" data-title="java"><pre v-pre class="language-java"><code><span class="token keyword">public</span> <span class="token keyword">void</span> <span class="token function">test</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">{</span>
    <span class="token keyword">int</span> result <span class="token operator">=</span> <span class="token class-name">FastChar</span>
                    <span class="token punctuation">.</span><span class="token function">getDB</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">.</span>
                    <span class="token function">update</span><span class="token punctuation">(</span><span class="token string">"update fc_user set userNickName = ? where userRole = ? "</span><span class="token punctuation">,</span> <span class="token string">"新的昵称"</span><span class="token punctuation">,</span><span class="token number">1</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
                    
    <span class="token comment">//result 代表受影响的行数</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="insert插入数据" tabindex="-1"><a class="header-anchor" href="#insert插入数据"><span>insert插入数据</span></a></h2>
<p>方法 <code v-pre>insert(String sqlStr, Object... params)</code> 执行更新sql语句，如下：</p>
<div class="language-java line-numbers-mode" data-ext="java" data-title="java"><pre v-pre class="language-java"><code><span class="token keyword">public</span> <span class="token keyword">void</span> <span class="token function">test</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">{</span>
    <span class="token keyword">int</span> result <span class="token operator">=</span> <span class="token class-name">FastChar</span>
            <span class="token punctuation">.</span><span class="token function">getDB</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
            <span class="token punctuation">.</span><span class="token function">insert</span><span class="token punctuation">(</span><span class="token string">"insert into fc_user values ( ? , ? , ? )  "</span><span class="token punctuation">,</span> <span class="token string">"用户昵称"</span><span class="token punctuation">,</span><span class="token string">"手机号码"</span><span class="token punctuation">,</span><span class="token number">1</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token comment">//result 返回数据的主键值</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="batch批量执行多个sql" tabindex="-1"><a class="header-anchor" href="#batch批量执行多个sql"><span>batch批量执行多个sql</span></a></h2>
<p>方法 <code v-pre>batch(String[] sqlArray, int batchSize)</code> 执行更新sql语句，如下：</p>
<div class="language-java line-numbers-mode" data-ext="java" data-title="java"><pre v-pre class="language-java"><code><span class="token keyword">public</span> <span class="token keyword">void</span> <span class="token function">test</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">{</span>
    <span class="token keyword">int</span><span class="token punctuation">[</span><span class="token punctuation">]</span> result <span class="token operator">=</span> <span class="token class-name">FastChar</span>
            <span class="token punctuation">.</span><span class="token function">getDB</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
            <span class="token punctuation">.</span><span class="token function">batch</span><span class="token punctuation">(</span><span class="token keyword">new</span> <span class="token class-name">String</span><span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token punctuation">{</span><span class="token string">"sql1"</span><span class="token punctuation">,</span><span class="token string">"sql2"</span><span class="token punctuation">,</span>……<span class="token punctuation">}</span><span class="token punctuation">,</span> <span class="token number">10000</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token comment">//result 执行批量 索引对应的sql 执行受影响行数</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="batch批量执行单个sql" tabindex="-1"><a class="header-anchor" href="#batch批量执行单个sql"><span>batch批量执行单个sql</span></a></h2>
<p>方法 <code v-pre>batch(String sqlStr, List&lt;Object[]&gt; params, int batchSize)</code> 执行更新sql语句，如下：</p>
<div class="language-java line-numbers-mode" data-ext="java" data-title="java"><pre v-pre class="language-java"><code><span class="token keyword">public</span> <span class="token keyword">void</span> <span class="token function">test</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">{</span>
    <span class="token class-name">List</span><span class="token operator">&lt;</span><span class="token class-name">Object</span><span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token operator">></span> params <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">ArrayList</span><span class="token generics"><span class="token punctuation">&lt;</span><span class="token punctuation">></span></span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token comment">//批量插入fc_user表的数据参数</span>
    
    <span class="token keyword">int</span><span class="token punctuation">[</span><span class="token punctuation">]</span> result <span class="token operator">=</span> <span class="token class-name">FastChar</span>
            <span class="token punctuation">.</span><span class="token function">getDB</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
            <span class="token punctuation">.</span><span class="token function">batch</span><span class="token punctuation">(</span><span class="token string">"insert into fc_user values ( ? , ? , ? )"</span><span class="token punctuation">,</span>params<span class="token punctuation">,</span> <span class="token number">10000</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token comment">//result 执行批量 索引对应的sql 执行受影响行数</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="单个事务执行" tabindex="-1"><a class="header-anchor" href="#单个事务执行"><span>单个事务执行</span></a></h2>
<p>方法 <code v-pre>beginTransaction</code> 开启事务，</p>
<p>方法 <code v-pre>endTransaction</code> 结束事务，</p>
<p>方法 <code v-pre>rollbackTransaction</code> 回滚事务。</p>
<p>如下：</p>
<div class="language-java line-numbers-mode" data-ext="java" data-title="java"><pre v-pre class="language-java"><code><span class="token keyword">public</span> <span class="token keyword">void</span> <span class="token function">test</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token class-name">FastDB</span> fastDB <span class="token operator">=</span> <span class="token class-name">FastChar</span><span class="token punctuation">.</span><span class="token function">getDB</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token keyword">try</span> <span class="token punctuation">{</span>
        fastDB<span class="token punctuation">.</span><span class="token function">beginTransaction</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span><span class="token comment">//开启一个事务</span>
        
        fastDB<span class="token punctuation">.</span><span class="token function">setLog</span><span class="token punctuation">(</span><span class="token boolean">false</span><span class="token punctuation">)</span>
                <span class="token punctuation">.</span><span class="token function">batch</span><span class="token punctuation">(</span>realSqlStr<span class="token punctuation">,</span> <span class="token number">100000</span><span class="token punctuation">)</span><span class="token punctuation">;</span><span class="token comment">//批量执行sql</span>
                
        fastDB<span class="token punctuation">.</span><span class="token function">endTransaction</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span><span class="token comment">//结束并提交事务</span>
    <span class="token punctuation">}</span> <span class="token keyword">catch</span> <span class="token punctuation">(</span><span class="token class-name">Exception</span> e<span class="token punctuation">)</span> <span class="token punctuation">{</span>
        e<span class="token punctuation">.</span><span class="token function">printStackTrace</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
        fastDB<span class="token punctuation">.</span><span class="token function">rollbackTransaction</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span><span class="token comment">//回滚事务</span>
    <span class="token punctuation">}</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="线程事务执行" tabindex="-1"><a class="header-anchor" href="#线程事务执行"><span>线程事务执行</span></a></h2>
<p>FastChar允许开发者开启线程事务，线程事务开启后，在同一个线程下，通过 <code v-pre>FastDB</code> 执行的sql语句统一交由事务处理。如下：</p>
<div class="language-java line-numbers-mode" data-ext="java" data-title="java"><pre v-pre class="language-java"><code>
<span class="token keyword">public</span> <span class="token keyword">void</span> <span class="token function">test</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token comment">//开启一个线程事务</span>
    <span class="token class-name">FastChar</span><span class="token punctuation">.</span><span class="token function">beginDatabaseThreadTransaction</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token keyword">try</span> <span class="token punctuation">{</span>
        <span class="token class-name">FastChar</span><span class="token punctuation">.</span><span class="token function">getDB</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">setLog</span><span class="token punctuation">(</span><span class="token boolean">false</span><span class="token punctuation">)</span>
                <span class="token punctuation">.</span><span class="token function">batch</span><span class="token punctuation">(</span>realSqlStr<span class="token punctuation">,</span> <span class="token number">100000</span><span class="token punctuation">)</span><span class="token punctuation">;</span><span class="token comment">//批量执行sql</span>
        
        <span class="token class-name">FcUserEntity</span><span class="token punctuation">.</span><span class="token function">dao</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">addUser</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span><span class="token comment">//执行其他方法</span>
        
        <span class="token class-name">FcDeptEntity</span><span class="token punctuation">.</span><span class="token function">dao</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">addDept</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span><span class="token comment">//执行其他方法</span>
                
        <span class="token class-name">FastChar</span><span class="token punctuation">.</span><span class="token function">endDatabaseThreadTransaction</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span><span class="token comment">//结束并统一提交事务</span>
    <span class="token punctuation">}</span> <span class="token keyword">catch</span> <span class="token punctuation">(</span><span class="token class-name">Exception</span> e<span class="token punctuation">)</span> <span class="token punctuation">{</span>
        e<span class="token punctuation">.</span><span class="token function">printStackTrace</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token class-name">FastChar</span><span class="token punctuation">.</span><span class="token function">rollbackDatabaseThreadTransaction</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span><span class="token comment">//回滚事务</span>
    <span class="token punctuation">}</span>
<span class="token punctuation">}</span>

</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>


