import comp from "/Users/Janesen/工作/space_webstorm/fastchar-docs/src/.vuepress/.temp/pages/guide/param-converter-info.html.vue"
const data = JSON.parse("{\"path\":\"/guide/param-converter-info.html\",\"title\":\"参数转换器\",\"lang\":\"zh-CN\",\"frontmatter\":{\"description\":\"参数转换器 IFastParamConverter 接口是FastChar 核心组件之一，用于 FastAction 方法中 将 请求的参数值 转换成对应的类型。 实现一个参数转换器 开发者可以自定义实现 IFastParamConverter 类，进行参数类型的转换，如下： 注册转换器 开发者实现一个参数转换器后，需要将该实现类注册到系统中才能被系统...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://www.fastchar.com/guide/param-converter-info.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"FastChar\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"参数转换器\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"参数转换器 IFastParamConverter 接口是FastChar 核心组件之一，用于 FastAction 方法中 将 请求的参数值 转换成对应的类型。 实现一个参数转换器 开发者可以自定义实现 IFastParamConverter 类，进行参数类型的转换，如下： 注册转换器 开发者实现一个参数转换器后，需要将该实现类注册到系统中才能被系统...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"参数转换器\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[]}\"]]},\"headers\":[{\"level\":2,\"title\":\"实现一个参数转换器\",\"slug\":\"实现一个参数转换器\",\"link\":\"#实现一个参数转换器\",\"children\":[]},{\"level\":2,\"title\":\"注册转换器\",\"slug\":\"注册转换器\",\"link\":\"#注册转换器\",\"children\":[]},{\"level\":2,\"title\":\"使用转换器\",\"slug\":\"使用转换器\",\"link\":\"#使用转换器\",\"children\":[]},{\"level\":2,\"title\":\"内置转换器\",\"slug\":\"内置转换器\",\"link\":\"#内置转换器\",\"children\":[{\"level\":3,\"title\":\"FastStringParamConverter\",\"slug\":\"faststringparamconverter\",\"link\":\"#faststringparamconverter\",\"children\":[]},{\"level\":3,\"title\":\"FastNumberParamConverter\",\"slug\":\"fastnumberparamconverter\",\"link\":\"#fastnumberparamconverter\",\"children\":[]},{\"level\":3,\"title\":\"FastBooleanParamConverter\",\"slug\":\"fastbooleanparamconverter\",\"link\":\"#fastbooleanparamconverter\",\"children\":[]},{\"level\":3,\"title\":\"FastDateParamConverter\",\"slug\":\"fastdateparamconverter\",\"link\":\"#fastdateparamconverter\",\"children\":[]},{\"level\":3,\"title\":\"FastEntityParamConverter\",\"slug\":\"fastentityparamconverter\",\"link\":\"#fastentityparamconverter\",\"children\":[]},{\"level\":3,\"title\":\"FastEnumParamConverter\",\"slug\":\"fastenumparamconverter\",\"link\":\"#fastenumparamconverter\",\"children\":[]},{\"level\":3,\"title\":\"FastFileParamConverter\",\"slug\":\"fastfileparamconverter\",\"link\":\"#fastfileparamconverter\",\"children\":[]},{\"level\":3,\"title\":\"参数类型说明\",\"slug\":\"参数类型说明\",\"link\":\"#参数类型说明\",\"children\":[]}]}],\"readingTime\":{\"minutes\":2.91,\"words\":873},\"filePathRelative\":\"guide/param-converter-info.md\",\"autoDesc\":true}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
