<template><div><h1 id="内容加解密组件" tabindex="-1"><a class="header-anchor" href="#内容加解密组件"><span>内容加解密组件</span></a></h1>
<h2 id="介绍" tabindex="-1"><a class="header-anchor" href="#介绍"><span>介绍</span></a></h2>
<p>FastChar核心组件，内置了内容的加解密功能，包含MD5、AES、RSA。</p>
<h2 id="使用" tabindex="-1"><a class="header-anchor" href="#使用"><span>使用</span></a></h2>
<p>开发者可以直接通过静态方法  <code v-pre>FastChar.getSecurity()</code> 选择调用加密的方法。</p>
<h2 id="md5加密" tabindex="-1"><a class="header-anchor" href="#md5加密"><span>MD5加密</span></a></h2>
<p>方法 <code v-pre>FastChar.getSecurity().MD5_Encrypt(String value)</code> 如下：</p>
<div class="language-java line-numbers-mode" data-highlighter="shiki" data-ext="java" data-title="java" style="--shiki-light:#24292e;--shiki-dark:#abb2bf;--shiki-light-bg:#fff;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes github-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#D73A49;--shiki-dark:#C678DD">public</span><span style="--shiki-light:#D73A49;--shiki-dark:#C678DD"> void</span><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF"> test</span><span style="--shiki-light:#24292E;--shiki-dark:#E06C75">() {</span></span>
<span class="line"><span style="--shiki-light:#D73A49;--shiki-dark:#C678DD">    try</span><span style="--shiki-light:#24292E;--shiki-dark:#E06C75"> {</span></span>
<span class="line"><span style="--shiki-light:#6A737D;--shiki-dark:#7F848E;--shiki-light-font-style:inherit;--shiki-dark-font-style:italic">        //MD5加密</span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#E5C07B">        FastChar</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">.</span><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">getSecurity</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">().</span><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">MD5_Encrypt</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">(</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379">"password"</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">);</span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#E06C75">    } </span><span style="--shiki-light:#D73A49;--shiki-dark:#C678DD">catch</span><span style="--shiki-light:#24292E;--shiki-dark:#E06C75"> (</span><span style="--shiki-light:#24292E;--shiki-dark:#E5C07B">Exception</span><span style="--shiki-light:#E36209;--shiki-dark:#E06C75;--shiki-light-font-style:inherit;--shiki-dark-font-style:italic"> e</span><span style="--shiki-light:#24292E;--shiki-dark:#E06C75">) {</span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#E5C07B">        e</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">.</span><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">printStackTrace</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">();</span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#E06C75">    }</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#E06C75">}</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="aes加解密" tabindex="-1"><a class="header-anchor" href="#aes加解密"><span>AES加解密</span></a></h2>
<p>加密方法 <code v-pre>FastChar.getSecurity().AES_Encrypt(String password,String value)</code></p>
<p>解密方法 <code v-pre>FastChar.getSecurity().AES_Decrypt(String password,String value)</code></p>
<p>如下示例：</p>
<div class="language-java line-numbers-mode" data-highlighter="shiki" data-ext="java" data-title="java" style="--shiki-light:#24292e;--shiki-dark:#abb2bf;--shiki-light-bg:#fff;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes github-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#D73A49;--shiki-dark:#C678DD">public</span><span style="--shiki-light:#D73A49;--shiki-dark:#C678DD"> void</span><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF"> test</span><span style="--shiki-light:#24292E;--shiki-dark:#E06C75">() {</span></span>
<span class="line"><span style="--shiki-light:#D73A49;--shiki-dark:#C678DD">    try</span><span style="--shiki-light:#24292E;--shiki-dark:#E06C75"> {</span></span>
<span class="line"><span style="--shiki-light:#6A737D;--shiki-dark:#7F848E;--shiki-light-font-style:inherit;--shiki-dark-font-style:italic">        //AES加密</span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#E5C07B">        FastChar</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">.</span><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">getSecurity</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">().</span><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">AES_Encrypt</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">(</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379">"123456"</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">, </span><span style="--shiki-light:#032F62;--shiki-dark:#98C379">"内容"</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">);</span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#E06C75">    </span></span>
<span class="line"><span style="--shiki-light:#6A737D;--shiki-dark:#7F848E;--shiki-light-font-style:inherit;--shiki-dark-font-style:italic">        //AES解密</span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#E5C07B">        FastChar</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">.</span><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">getSecurity</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">().</span><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">AES_Decrypt</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">(</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379">"123456"</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">, </span><span style="--shiki-light:#032F62;--shiki-dark:#98C379">"RrtydXXqFXrC14OZ7RQLsw=="</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">);</span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#E06C75">        </span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#E06C75">    } </span><span style="--shiki-light:#D73A49;--shiki-dark:#C678DD">catch</span><span style="--shiki-light:#24292E;--shiki-dark:#E06C75"> (</span><span style="--shiki-light:#24292E;--shiki-dark:#E5C07B">Exception</span><span style="--shiki-light:#E36209;--shiki-dark:#E06C75;--shiki-light-font-style:inherit;--shiki-dark-font-style:italic"> e</span><span style="--shiki-light:#24292E;--shiki-dark:#E06C75">) {</span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#E5C07B">        e</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">.</span><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">printStackTrace</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">();</span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#E06C75">    }</span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#E06C75">}</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="rsa加解密" tabindex="-1"><a class="header-anchor" href="#rsa加解密"><span>RSA加解密</span></a></h2>
<div class="hint-container warning">
<p class="hint-container-title">Java使用RSA关键参数说明</p>
<p>rsa加密的 <code v-pre>padding</code> 值 <code v-pre>RSA/NONE/PKCS1Padding</code></p>
</div>
<h3 id="公钥加密-私钥解密" tabindex="-1"><a class="header-anchor" href="#公钥加密-私钥解密"><span>公钥加密-私钥解密</span></a></h3>
<p>加密方法 <code v-pre>FastChar.getSecurity().RSA_Encrypt_PublicKey(String publicKey,String value)</code></p>
<p>解密方法：<code v-pre>FastChar.getSecurity().RSA_Decrypt_PrivateKey(String privateKey,String value)</code></p>
<p>如下示例：</p>
<div class="language-java line-numbers-mode" data-highlighter="shiki" data-ext="java" data-title="java" style="--shiki-light:#24292e;--shiki-dark:#abb2bf;--shiki-light-bg:#fff;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes github-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#D73A49;--shiki-dark:#C678DD">public</span><span style="--shiki-light:#D73A49;--shiki-dark:#C678DD"> void</span><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF"> test</span><span style="--shiki-light:#24292E;--shiki-dark:#E06C75">() {</span></span>
<span class="line"><span style="--shiki-light:#D73A49;--shiki-dark:#C678DD">    try</span><span style="--shiki-light:#24292E;--shiki-dark:#E06C75"> {</span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#E06C75">        </span></span>
<span class="line"><span style="--shiki-light:#6A737D;--shiki-dark:#7F848E;--shiki-light-font-style:inherit;--shiki-dark-font-style:italic">        //使用公钥 rsa_public_1024.pem 加密</span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#E5C07B">        FastChar</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">.</span><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">getSecurity</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">().</span><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">RSA_Encrypt_PublicKey</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">(</span><span style="--shiki-light:#24292E;--shiki-dark:#E5C07B">FastFileUtils</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">.</span><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">readFileToString</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">(</span><span style="--shiki-light:#D73A49;--shiki-dark:#C678DD">new</span><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF"> File</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">(</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379">"rsa_public_1024.pem"</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">)), </span><span style="--shiki-light:#032F62;--shiki-dark:#98C379">"内容"</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">);</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#6A737D;--shiki-dark:#7F848E;--shiki-light-font-style:inherit;--shiki-dark-font-style:italic">        //使用私钥 rsa_private_pkcs8_1024.pem 解密</span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#E5C07B">        FastChar</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">.</span><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">getSecurity</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">().</span><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">RSA_Decrypt_PrivateKey</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">(</span><span style="--shiki-light:#24292E;--shiki-dark:#E5C07B">FastFileUtils</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">.</span><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">readFileToString</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">(</span><span style="--shiki-light:#D73A49;--shiki-dark:#C678DD">new</span><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF"> File</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">(</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379">"rsa_private_pkcs8_1024.pem"</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">)), </span><span style="--shiki-light:#032F62;--shiki-dark:#98C379">"qpcuCKJ3vEDjGI+J4ho/t177tuyEFO3sM5v5lcsw5TYGpBSrdu8W9Gwsr9alPMqBux5Bk7fVTmQo</span><span style="--shiki-light:#005CC5;--shiki-dark:#56B6C2">\n</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379">"</span><span style="--shiki-light:#D73A49;--shiki-dark:#56B6C2"> +</span></span>
<span class="line"><span style="--shiki-light:#032F62;--shiki-dark:#98C379">                "F2XeaXtKwMGy/ck2GdqYFSPoXliX2LGOB+DDjLeaWNwNwPpnR4U8TUH2a3bnixgezrnVIjZ3G5hb</span><span style="--shiki-light:#005CC5;--shiki-dark:#56B6C2">\n</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379">"</span><span style="--shiki-light:#D73A49;--shiki-dark:#56B6C2"> +</span></span>
<span class="line"><span style="--shiki-light:#032F62;--shiki-dark:#98C379">                "EV5aokVTR/dxVEor0C0="</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">);</span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#E06C75">        </span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#E06C75">    } </span><span style="--shiki-light:#D73A49;--shiki-dark:#C678DD">catch</span><span style="--shiki-light:#24292E;--shiki-dark:#E06C75"> (</span><span style="--shiki-light:#24292E;--shiki-dark:#E5C07B">Exception</span><span style="--shiki-light:#E36209;--shiki-dark:#E06C75;--shiki-light-font-style:inherit;--shiki-dark-font-style:italic"> e</span><span style="--shiki-light:#24292E;--shiki-dark:#E06C75">) {</span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#E5C07B">        e</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">.</span><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">printStackTrace</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">();</span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#E06C75">    }</span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#E06C75">}</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="私钥加密-公钥解密" tabindex="-1"><a class="header-anchor" href="#私钥加密-公钥解密"><span>私钥加密-公钥解密</span></a></h3>
<p>加密方法 <code v-pre>FastChar.getSecurity().RSA_Encrypt_PrivateKey(String privateKey,String value)</code></p>
<p>解密方法：<code v-pre>FastChar.getSecurity().RSA_Decrypt_PublicKey(String publicKey,String value)</code></p>
<p>如下示例：</p>
<div class="language-java line-numbers-mode" data-highlighter="shiki" data-ext="java" data-title="java" style="--shiki-light:#24292e;--shiki-dark:#abb2bf;--shiki-light-bg:#fff;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes github-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#D73A49;--shiki-dark:#C678DD">public</span><span style="--shiki-light:#D73A49;--shiki-dark:#C678DD"> void</span><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF"> test</span><span style="--shiki-light:#24292E;--shiki-dark:#E06C75">() {</span></span>
<span class="line"><span style="--shiki-light:#D73A49;--shiki-dark:#C678DD">    try</span><span style="--shiki-light:#24292E;--shiki-dark:#E06C75"> {</span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#E06C75">        </span></span>
<span class="line"><span style="--shiki-light:#6A737D;--shiki-dark:#7F848E;--shiki-light-font-style:inherit;--shiki-dark-font-style:italic">        //使用私钥 rsa_private_pkcs8_1024.pem 加密</span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#E5C07B">        FastChar</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">.</span><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">getSecurity</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">().</span><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">RSA_Encrypt_PrivateKey</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">(</span><span style="--shiki-light:#24292E;--shiki-dark:#E5C07B">FastFileUtils</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">.</span><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">readFileToString</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">(</span><span style="--shiki-light:#D73A49;--shiki-dark:#C678DD">new</span><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF"> File</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">(</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379">"rsa_private_pkcs8_1024.pem"</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">)), </span><span style="--shiki-light:#032F62;--shiki-dark:#98C379">"内容"</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">);</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#6A737D;--shiki-dark:#7F848E;--shiki-light-font-style:inherit;--shiki-dark-font-style:italic">        //使用公钥 rsa_public_1024.pem 解密</span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#E5C07B">        FastChar</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">.</span><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">getSecurity</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">().</span><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">RSA_Decrypt_PublicKey</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">(</span><span style="--shiki-light:#24292E;--shiki-dark:#E5C07B">FastFileUtils</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">.</span><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">readFileToString</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">(</span><span style="--shiki-light:#D73A49;--shiki-dark:#C678DD">new</span><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF"> File</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">(</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379">"rsa_public_1024.pem"</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">)), </span><span style="--shiki-light:#032F62;--shiki-dark:#98C379">"qpcuCKJ3vEDjGI+J4ho/t177tuyEFO3sM5v5lcsw5TYGpBSrdu8W9Gwsr9alPMqBux5Bk7fVTmQo</span><span style="--shiki-light:#005CC5;--shiki-dark:#56B6C2">\n</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379">"</span><span style="--shiki-light:#D73A49;--shiki-dark:#56B6C2"> +</span></span>
<span class="line"><span style="--shiki-light:#032F62;--shiki-dark:#98C379">                "F2XeaXtKwMGy/ck2GdqYFSPoXliX2LGOB+DDjLeaWNwNwPpnR4U8TUH2a3bnixgezrnVIjZ3G5hb</span><span style="--shiki-light:#005CC5;--shiki-dark:#56B6C2">\n</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379">"</span><span style="--shiki-light:#D73A49;--shiki-dark:#56B6C2"> +</span></span>
<span class="line"><span style="--shiki-light:#032F62;--shiki-dark:#98C379">                "EV5aokVTR/dxVEor0C0="</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">);</span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#E06C75">        </span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#E06C75">    } </span><span style="--shiki-light:#D73A49;--shiki-dark:#C678DD">catch</span><span style="--shiki-light:#24292E;--shiki-dark:#E06C75"> (</span><span style="--shiki-light:#24292E;--shiki-dark:#E5C07B">Exception</span><span style="--shiki-light:#E36209;--shiki-dark:#E06C75;--shiki-light-font-style:inherit;--shiki-dark-font-style:italic"> e</span><span style="--shiki-light:#24292E;--shiki-dark:#E06C75">) {</span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#E5C07B">        e</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">.</span><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">printStackTrace</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">();</span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#E06C75">    }</span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#E06C75">}</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="上述示例中的公钥与私钥" tabindex="-1"><a class="header-anchor" href="#上述示例中的公钥与私钥"><span>上述示例中的公钥与私钥</span></a></h3>
<Tabs id="72" :data='[{"id":"rsa_public_1024.pem"},{"id":"rsa_private_pkcs8_1024.pem"}]'>
<template #title0="{ value, isActive }">rsa_public_1024.pem</template>
<template #title1="{ value, isActive }">rsa_private_pkcs8_1024.pem</template>
<template #tab0="{ value, isActive }">
<div class="language-text line-numbers-mode" data-highlighter="shiki" data-ext="text" data-title="text" style="--shiki-light:#24292e;--shiki-dark:#abb2bf;--shiki-light-bg:#fff;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes github-light one-dark-pro vp-code"><code><span class="line"><span>MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCyGgxpYR0aNkKRw9xvNrgdFbWp</span></span>
<span class="line"><span>DkmP3+TXcVyipU+IjWnxjDAh8cXcR1+mNT9a8k0rJbDgDUpfr6jNMqelIadKCqxK</span></span>
<span class="line"><span>TDdvIwyg/BR39+KORNwb86GLNXa4GBAhB4v2HMFmaVAdQSBFy4/mIzIlNYk4DLnX</span></span>
<span class="line"><span>cXNJUDWwetzk4dcWTwIDAQAB</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></template>
<template #tab1="{ value, isActive }">
<div class="language-text line-numbers-mode" data-highlighter="shiki" data-ext="text" data-title="text" style="--shiki-light:#24292e;--shiki-dark:#abb2bf;--shiki-light-bg:#fff;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes github-light one-dark-pro vp-code"><code><span class="line"><span>MIICdwIBADANBgkqhkiG9w0BAQEFAASCAmEwggJdAgEAAoGBALIaDGlhHRo2QpHD</span></span>
<span class="line"><span>3G82uB0VtakOSY/f5NdxXKKlT4iNafGMMCHxxdxHX6Y1P1ryTSslsOANSl+vqM0y</span></span>
<span class="line"><span>p6Uhp0oKrEpMN28jDKD8FHf34o5E3BvzoYs1drgYECEHi/YcwWZpUB1BIEXLj+Yj</span></span>
<span class="line"><span>MiU1iTgMuddxc0lQNbB63OTh1xZPAgMBAAECgYEApNDGO57LN76OzCXckG6q4v98</span></span>
<span class="line"><span>JP47xREEzPrzJvCkMVHsgMOip0b+O2MxeLY98wPXtd4jWLPz56i/JWWDDqWeELMQ</span></span>
<span class="line"><span>L636a18zwp0iU2/8/d3cG0Mumecfl3HCbmzLJj2J6UKty3JisFVLa4IKDKye4T6+</span></span>
<span class="line"><span>I8OX6rgbv2qn+bJKjcECQQDhs4ve9H9UziwrZAwSYbiex6swv2XmE359ki42URPX</span></span>
<span class="line"><span>N3yDaNZAFZyAo7NvKu6jJtIgcqhHORRmEdVUrvMx5O39AkEAygKxq4WfxGMfEqb2</span></span>
<span class="line"><span>vkvLCIp1BOSoLFRWzsIGeVLYx51nOlQ5Do6VeHXv2iEnJSlfNomypxaWgX9e/RXq</span></span>
<span class="line"><span>jXNBOwJAE1ETkoRodXCj1R7d7aDRdT1viF+JMBTRCZw+OkXcJdpI3NJXK+rtlxDr</span></span>
<span class="line"><span>pYMOI4aKC17kyhu3hDjYgkPq6oVGXQJAYop34sSXD/SONsoNePx9+ReZR57GzoEB</span></span>
<span class="line"><span>q3AIOmyIZK9KqLBm+Mvi69UUAGLFtqH82RzIcitZlaftTSXAuelr+wJBAKv+WRag</span></span>
<span class="line"><span>9JN5JjNiE5vo27RaQ/raS2qlW0/3dxCM02Sgk4H9U72dOULDCHC8/ij47prIN7Zs</span></span>
<span class="line"><span>zyP55j7fPQrPnZs=</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></template>
</Tabs>
</div></template>


